name: deploy-model

# trigger when commit is pushed to model/app/
on:
  workflow_dispatch:
  push:
    paths:
      - 'model/app/*'

jobs:
  build:
    name: Model Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      # checkout the repo
      - name: Checkout
        id: checkout
        uses: actions/checkout@master

      # configure GCP CLI
      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/model:latest model/app/
      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/model:latest
      - name: Deploy
        run: |
          gcloud run deploy model \
          --region us-east1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/model \
          --platform managed \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --service-account ${{ secrets.MODEL_SA }}
